gutenberg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ebooks/(?P<pk>\d+)/$', views.book_detail, name='book_detail'),
    url(r'^subject/(?P<pk>\d+)/$', views.subject, name='subject'),
    url(r'^bookshelf/(?P<pk>\d+)/$', views.bookshelf, name='bookshelf'),
]

gutenberg/models.py
import json
import requests
from os.path import basename
from django.db import models
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from django.conf import settings

from base.utils import sizeof_fmt

import logging
log = logging.getLogger(__name__)


COMMON_STR_LEN = 200

def show_str(s, n=50):
    if len(s) < n:
        return s
    else:
        return s[:n] + '...'


class BaseItem(models.Model):
    name = models.CharField(max_length=COMMON_STR_LEN, unique=True)
    display = models.CharField(max_length=COMMON_STR_LEN, blank=True, null=True)
    count = models.PositiveIntegerField(default=0)

    class Meta:
        abstract = True
        ordering = ['-count', 'name']

    @property
    def display_name(self):
        return self.display or self.name

    @property
    def display_count(self):
        return '({})'.format(self.count) if self.count else ''

    def __str__(self):
        return '{}{}'.format(self.display_name, self.display_count)

    def update_count(self):
        self.count = self.book_set.all().count()
        self.save(update_fields=['count'])


class Subject(BaseItem):
    pass


class Language(BaseItem):
    pass


class Bookshelf(BaseItem):
    pass


class Category(BaseItem):
    pass


class Author(models.Model):
    name = models.CharField(max_length=COMMON_STR_LEN)
    aliases = ArrayField(models.CharField(max_length=COMMON_STR_LEN), blank=True)
    webpage = models.URLField(blank=True, null=True, default='')
    # actually year only, can be minus like -345
    birthdate = models.SmallIntegerField(blank=True, null=True)
    deathdate = models.SmallIntegerField(blank=True, null=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    id = models.PositiveIntegerField("EBook-No.", primary_key=True)
    title = models.CharField(max_length=COMMON_STR_LEN)
    alternative = models.CharField(max_length=COMMON_STR_LEN, blank=True)
    issued = models.DateField('Release Date', blank=True, null=True)
    downloads = models.PositiveIntegerField(default=0)

    cover_small = models.URLField(blank=True, default='')
    cover_medium = models.URLField(blank=True, default='')

    category = models.ForeignKey(Category, blank=True, null=True)
    languages = models.ManyToManyField(Language, blank=True)
    authors = models.ManyToManyField(Author, blank=True)
    subjects = models.ManyToManyField(Subject, blank=True)
    bookshelves = models.ManyToManyField(Bookshelf, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    push_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-downloads']

    def __str__(self):
        return show_str(self.title)

    def cover(self, size='small'):
        return self.cover_small or self.cover_medium or ''

    def get_absolute_url(self):
        return reverse('gutenberg:book_detail', kwargs={'pk': self.pk})


class File(models.Model):
    book = models.ForeignKey(Book)
    uri = models.URLField(unique=True)
    format = models.CharField(max_length=50)
    is_zip = models.BooleanField(default=False)
    modified_at = models.DateTimeField(blank=True, null=True, db_index=True)
    size = models.PositiveIntegerField(default=0)

    push_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-modified_at']

    def basename(self):
        """
        Get uri basename.

        For legacy reason, this is a method, not property
        """
        return basename(self.uri)

    @property
    def name(self):
        return self.basename()

    def get_attachment_name_and_data(self):
        # uri: http://www.gutenberg.org/ebooks/54506.kindle.noimages
        r = requests.get(self.uri)
        if r.ok:
            # real uri: http://www.gutenberg.org/cache/epub/54506/pg54506.mobi
            return basename(r.url), r.content

    def is_large(self):
        return self.size > settings.MAX_PUSHSIZE

    def __str__(self):
        return self.name

    @property
    def humansize(self):
        return sizeof_fmt(self.size)

    def can_push(self, device_mail):
        return not ('kindle' in device_mail and 'epub' in self.format)

    def has_pushed(self, user_id, device_mail, in_seconds=10):
        """
        Check whether user has pushed in seconds.

        Adaptor for gutenberg File obj.
        Pass user_id in case UserProxy was used.
        """
        from books.models import Push
        from datetime import datetime, timedelta
        when = datetime.now() - timedelta(seconds=in_seconds)
        return Push.objects.filter(
            file_uri=self.uri,
            user_id=user_id,
            email=device_mail,
            when__gt=when,
        ).exists()

    def create_push(self, **kwargs):
        from books.models import Push
        push = Push.objects.create(file_uri=self.uri, **kwargs)
        log.info('file {} push_count +1'.format(self.pk))
        self.__class__.objects.filter(id=self.id).update(push_count=models.F('push_count')+1)
        return push

gutenberg/forms.py
from django import forms
from . import models as m

class BookFilterForm(forms.Form):

    q = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '搜索关键字',
            }
        )
    )

    language = forms.ModelChoiceField(
        required=False,
        queryset=m.Language.objects.all(),
        empty_label='全部语言',
    )

    category = forms.ModelChoiceField(
        required=False,
        queryset=m.Category.objects.all(),
        empty_label='全部类别',
    )

    ORDER_BY_CHOICES = (
        ('downloads', '按下载数量'),
        ('id', '按收录顺序'),
        ('issued', '按出版日期'),
    )
    order_by = forms.ChoiceField(
        choices=ORDER_BY_CHOICES,
    )

    ORDER_CHOICES = (
        ('desc', '降序排序'),
        ('asc', '升序排序'),
    )
    order = forms.ChoiceField(
        choices=ORDER_CHOICES,
    )

gutenberg/views.py
from django.shortcuts import render
from django.db.models import Q
from django.shortcuts import get_object_or_404

from annoying.decorators import render_to

from base.utils import paging
from . import models as m
from . import forms as f


def T(template_name):
    return 'gutenberg/{}'.format(template_name)


def _book_list(request, objs):
    ctx = paging(request, objs)
    data = request.GET.dict()
    ctx['filter_form'] = f.BookFilterForm(initial=data)
    get_copy = request.GET.copy()
    get_copy.pop('page', '')
    ctx['querystring'] = get_copy.urlencode()
    ctx['gutenberg_active'] = 'active'
    return render(request, T('index.html'), context=ctx)


def index(request):
    objs = m.Book.objects.all()
    data = request.GET.dict()

    language = data.get('language', '')
    if language:
        objs = objs.filter(languages__id=language)

    category = data.get('category', '')
    if category:
        objs = objs.filter(category__id=category)

    q = data.get('q', '')
    if q:
        q0 = Q(title__icontains=q)
        q1 = Q(authors__name__icontains=q)
        q2 = Q(authors__aliases__icontains=q)
        q3 = Q(subjects__name__icontains=q)
        objs = objs.filter(q0 | q1 | q2 | q3)

    order_by = data.get('order_by', 'downloads')
    order = '' if data.get('order') == 'asc' else '-'
    ordering = order + order_by
    objs = objs.order_by(ordering).distinct()
    return _book_list(request, objs)


def subject(request, pk):
    objs = m.Book.objects.filter(subjects=pk)
    return _book_list(request, objs)


def bookshelf(request, pk):
    objs = m.Book.objects.filter(bookshelves=pk)
    return _book_list(request, objs)


def book_detail(request, pk):
    book = get_object_or_404(m.Book, pk=pk)
    pjax = request.META.get('HTTP_X_PJAX')
    ctx = {'obj': book, 'pjax': pjax, 'gutenberg_active': 'active'}
    tmpl = 'book_detail_inc.html' if pjax else 'book_detail.html'
    return render(request, T(tmpl), context=ctx)

gutenberg/templates/gutenberg/book_detail.html
{% extends "layout.html" %}

{% block title %}readfree.me-{{obj.title}}{% endblock %}
{% block tc_title %}{{obj.title}}{% endblock %}
{% block tc_desc %}{{obj.summary}}{% endblock %}
{% block tc_image %}{{obj.image}}{% endblock %}

{% block content %}
{% include 'gutenberg/book_detail_inc.html' %}
{% endblock %}

gutenberg/templates/gutenberg/book_detail_inc.html
{% extends 'split_inc.html' %}
{% load base_extra %}
{% load books_extra %}

{% block left %}
<div class="margin-medium well">

    {% if pjax %}
    <button id="pjax-close" type="button" class="close" tabindex="-1"
        data-dismiss="modal" aria-hidden="true">&times;</button>
    {% endif %}

    <h2>{{obj.title|shortzh:'100'}}</h2>

    <table class="table table-hover">
      <tbody>
        <tr>
          <th>作者</th>
          <td><ul class="unstyled inline">{% for author in obj.authors.all %}<li>{{author.name}}</li>{% endfor %}</ul></td>
        </tr>
        <tr>
            <th>语言</th>
            <td><ul class="unstyled inline">{% for language in obj.languages.all %}<li>{{language.name}}</li>{% endfor %}</ul></td>
        </tr>
        <tr>
            <th>类别</th>
            <td>{{obj.category}}</td>
        </tr>
        <tr>
            <th>发布日期</th>
            <td>{{obj.issued}}</td>
        </tr>
        <tr>
            <th>版权状态</th>
            <td>Public domain in the USA.</td>
        </tr>
        <tr>
            <th>过去30天下载次数</th>
            <td>{{obj.downloads}}</td>
        </tr>
      </tbody>
    </table>

    {% if obj.subjects.all.count  %}
    <h4>相关主题</h4>
    <ul class='unstyled inline well' id="book-tags">
        {% for s in obj.subjects.all %}
        <li><a href="{% url 'gutenberg:subject' s.pk %}">{{s}}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if obj.bookshelves.all.count  %}
    <h4>类似书籍</h4>
    <ul class='unstyled inline well' id="book-tags">
        {% for s in obj.bookshelves.all %}
        <li><a href="{% url 'gutenberg:bookshelf' s.pk %}">{{s}}</a></li>
        {% endfor %}
    </ul>
    {% endif %}


{% if user.id %}

<div class="alert alert-info">点击文件名可直接进入古腾堡网站查看或下载文件, 不占用本站下载额度. 推送会消耗额度.</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>文件</th>
      <th>推送</th>
      <th>大小</th>
    </tr>
  </thead>
  <tbody>
{% for e in obj.file_set.all %}
    <tr>
      <td><a target="_blank" href="{{e.uri}}">{{e.name}}</a></td>
      <td>

{% if can_push and balance_today %}
<div class="btn-group">
    {% with user.device_mails.first as default_device_mail %}
        {% if pushmail %}
        <button data-pk="{{e.pk}}" data-pushmail="{{default_device_mail}}"
            class='pushmail-required book-push gutenberg btn btn-mini {% if e.id in pushs %}btn-inverse{% else %}btn-success{% endif %}'>
            <i class="fa fa-paper-plane" aria-hidden="true"></i>推送<span class="push-num">{{e.push_count}}</span>
        </button>
        {% else %}
        <a class='btn btn-mini {% if e.id in pushs %}btn-inverse{% else %}btn-success{% endif %}' href="{% url 'accounts:push' %}">
            <i class="fa fa-paper-plane" aria-hidden="true"></i>推送
        </a>
        {% endif %}
        <button class="btn btn-mini {% if e.id in pushs %}btn-inverse{% else %}btn-success{% endif %} dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
    {% endwith %}
    <ul class="dropdown-menu">
        {% for device_mail in user.device_mails %}
        <li><a data-pk="{{e.pk}}" data-pushmail="{{device_mail}}" class="book-push gutenberg" href="#"><i class="fa fa-paper-plane"></i>推送到 {{device_mail}} {% if forloop.first %}(默认){% endif %}</a></li>
        {% endfor %}
        <li class="divider"></li>
        <li><a target="_blank" href="{% url 'accounts:profile' user.username 'push' %}"><i class="fa fa-align-left"></i>推送状态</a></li>
        <li><a target="_blank" href="{% url 'accounts:push' %}"><i class="fa fa-cog"></i>设置</a></li>
    </ul>
</div>
{% endif %}


      </td>
      <td>{{e.humansize}}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% else %}
<small>
    <a href="{% url 'accounts:signin' %}">登录</a>
</small>
{% endif %}

</div>
{% endblock %}

gutenberg/templates/gutenberg/file_meta.html
{% load books_extra %}
<li id={{e.pk}} pk={{e.pk}} ext={{e.ext}}>

<div>
    <span class="badge badge">{{e.humansize}}</span>
    <a href="{{ e.get_absolute_url }}"><span class="badge badge" title="{{e.basename}}">{{e.display}}</span></a>
    {% if e.is_new %}
    <span class="label label-info">新版本</span>
    {% endif %}
    <ul class="unstyled pull-right inline">
    <li>
    <a href="{% url 'edition' e.pk %}">
        <small>{{e.talks.count}}条评论</small>
        <i class="icon-comment icon-white"></i>
    </a>
    </li>
    </ul>
</div>
<div class="btn-toolbar">
{% if user.id %}
    {% include 'gutenberg/edition_btns.html' %}
{% else %}
    {% include 'books/edition_btns_guest.html' %}
{% endif %}
</div>
</li>

gutenberg/templates/gutenberg/index.html
{% extends 'gutenberg/subnavbar.html' %}
{% load base_extra %}
{% load books_extra %}


{% block books_header %}

<p class="alert alert-info">
<a href="http://www.gutenberg.org/" target="_blank">古腾堡工程</a>
(Project Gutenberg，缩写：PG)，由志愿者参与，致力于文化作品的数字化归档，
并鼓励创作发行电子书。该工程肇始于1971年，是最早的数字图书馆。
其中的大部分书籍都是公有领域书籍的原本，古腾堡工程确保这些原本以开放文件格式自由流通，有利于长期保存，并可在各种计算机上自由阅读。
大多数版本使用的语言是英语，但也有许多非英语作品。
截至2017年6月，古腾堡工程声称提供超过54,000件馆藏。</p>

<form id="gutenberg-search-form" class="form-inline" action="" method="get">
    {{ filter_form.q }}
    {{ filter_form.language }}
    {{ filter_form.category }}
    {{ filter_form.order_by }}
    {{ filter_form.order }}
    <button class="btn btn-primary" type="submit"><i class="fa fa-search">搜索</i></button>
    <a class="btn" href="{% url 'gutenberg:index' %}"><i class="fa fa-undo">重置</i></a>
</form>
{% endblock %}


{% block books_index %}
<ul class='unstyled book-index'>
{% for obj in page.object_list %}
<li class="book-item" data-pk={{obj.pk}}>
<div class="well book-card">
    <div class="book-cover" title="{{obj.title}}">
        {% if obj.cover %}
        <a class="pjax" href="{{obj.get_absolute_url}}">
            <img class='book-img img-rounded' src="{{obj.cover}}" alt="{{obj.title}}"/>
        </a>
        {% endif %}
    </div>
    <div class="book-info">
        <a class="pjax" href="{{obj.get_absolute_url}}" title="{{obj.title}}">
            {{ obj.title|shortzh:'30'}}
        </a>
        <div class="book-author">
            {{ obj.authors.all|slice:":2"|join:","|shortzh:'30'}}
        </div>
    </div>
    <div class='book-meta muted'>
        {% block book_stat %}
        <i class="fa fa-download" title='下载次数'></i>{{obj.downloads}}
        {% endblock book_stat %}
        <span class='douban'>
            <span title="出版日期">{{obj.issued}}</span>
        </span>
    </div>
</div>
</li>
{% endfor %}
<div class='clearfix'></div>
</ul>
{% endblock %}

gutenberg/templates/gutenberg/pagination_inc.html
{% if pager.num_pages > 1 %}
<div class="pagination pagination-centered">
    <ul>
        {% if page.has_previous %}
        <li><a title='上一页' href="?page={{ page.previous_page_number }}{% if querystring %}&{{querystring}}{% endif %}">&laquo;</a></li>
        {% else %}
        <li class='disabled'><span>&laquo;</span></li>
        {% endif %}

        {% for i in page_range %}
            {% if i == 0 %}
                <li class="hidden-phone"><span>...</span></li>
            {% elif i == page.number %}
                <li class='active'><span>{{i}}</span></li>
            {% else %}
                <li class="hidden-phone"><a href="?page={{i}}{% if querystring %}&{{querystring}}{% endif %}">{{i}}</a></li>
            {% endif %}
        {% endfor %}

        {% if page.has_next %}
        <li><a title='下一页' href="?page={{ page.next_page_number }}{% if querystring %}&{{querystring}}{% endif %}">&raquo;</a></li>
        {% else %}
        <li class='disabled'><span>&raquo;</span></li>
        {% endif %}
        <form id="go-to" class="form-inline pull-right" action="" method="get">
            <input class="input-mini" id="id_goto" name="page" type="number"
                min="1" max="{{pager.num_pages}}" value="{{go}}">
            <button type="submit" class="btn btn-small">
                <i class="icon-random"></i>
            </button>
        </form>
    </ul>
</div>
{% endif %}

gutenberg/templates/gutenberg/subnavbar.html
{% extends 'layout.html' %}
{% load base_extra %}
{% load books_extra %}


{% block content %}

{% block books_header %}
{% endblock %}

{% block books_index %}
{% endblock %}

{% block books_footer %}
{% include 'gutenberg/pagination_inc.html' %}
{% endblock %}

{% endblock content %}